@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR


Class JobAddressBook
Class ModelManager

Package Job {
Class Job
Class Name
Class Phone
Class Email
Class Address
Class Vacancy
Class Priority
Class UniqueJobList
}

Package Tag {
Class Tag
}

JobAddressBook -right[hidden]-ModelManager

Job *--> "2" Name
Job *--> Phone
Job *--> Email
Job *--> Address
Job *--> Vacancy
Job *--> Priority
Job *--> "*" Tag

@enduml