@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyPersonAddressBook <<Interface>>
Interface ReadOnlyJobAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class PersonAddressBook
Class JobAddressBook
Class ReadOnlyPersonAddressBook
Class ReadOnlyJobAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Information {
Class UniquePersonList
Class UniqueJobList
Class Person
Class Job
}

Package Tag {
Class Tag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ...> Model

PersonAddressBook .up.|> ReadOnlyPersonAddressBook
JobAddressBook .up.|> ReadOnlyJobAddressBook

PersonAddressBook *--> "1" UniquePersonList
JobAddressBook *--> "1" UniqueJobList

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o-right-> "1" PersonAddressBook
ModelManager o-left-> "1" JobAddressBook
UniquePersonList o--> "*" Person
UniqueJobList o--> "*" Job
ModelManager --> Job : filtered list
ModelManager --> Job : sorted list
ModelManager --> Person : filtered list
ModelManager --> Person : sorted list
ModelManager o-up-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Person *--> "*" Tag
Job *--> "*" Tag


@enduml
