@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface PersonAddressBookStorage <<Interface>>
Interface JobAddressBookStorage <<Interface>>

Class StorageManager
Class JsonAdaptedTag
Class JsonUserPrefsStorage
Class JsonPersonAddressBookStorage
Class JsonJobAddressBookStorage
Class JsonSerializablePersonAddressBookStorage
Class JsonSerializableJobAddressBookStorage

StorageManager .left.|> Storage
StorageManager o-right-> "1" UserPrefsStorage
JsonUserPrefsStorage .left.|> UserPrefsStorage

StorageManager o--> "1" PersonAddressBookStorage
StorageManager o--> "1" JobAddressBookStorage

JsonPersonAddressBookStorage .right.|> PersonAddressBookStorage
JsonPersonAddressBookStorage .down.> JsonSerializablePersonAddressBookStorage
JsonSerializablePersonAddressBookStorage .down.> JsonSerializablePerson
JsonSerializablePerson .down.> JsonAdaptedTag
JsonSerializablePerson .down.> JsonAdaptedPerson

JsonJobAddressBookStorage .left.|> JobAddressBookStorage
JsonJobAddressBookStorage .down.> JsonSerializableJobAddressBookStorage
JsonSerializableJobAddressBookStorage .down.> JsonSerializableJob
JsonSerializableJob .down.> JsonAdaptedTag
JsonSerializableJob .down.> JsonAdaptedJob
@enduml
