/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from lightest to darkest

!define UI_COLOR #DABCEB
!define UI_COLOR_T1 #E1D5E7
!define UI_COLOR_T2 #AB68D1
!define UI_COLOR_T3 #8233B0
!define UI_COLOR_T4 #3E0C59

!define LOGIC_COLOR #7AD1D6
!define LOGIC_COLOR_T1 #B0E3E6
!define LOGIC_COLOR_T2 #50C0C6
!define LOGIC_COLOR_T3 #2AA2A9
!define LOGIC_COLOR_T4 #0E858B

!define MODEL_COLOR #F7E2A4
!define MODEL_COLOR_T1 #FFF2CC
!define MODEL_COLOR_T2 #F8D879
!define MODEL_COLOR_T3 #EDC345
!define MODEL_COLOR_T4 #E5AF0E

!define STORAGE_COLOR #F8C2BB
!define STORAGE_COLOR_T1 #FAD9D5
!define STORAGE_COLOR_T2 #EEABA3
!define STORAGE_COLOR_T3 #E9948A
!define STORAGE_COLOR_T4 #E46F62

!define USER_COLOR #000000

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #000000
    BorderThickness 1
    BorderColor #FFFFFF
    StereotypeFontColor #000000
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #000000
    FontName Arial
}

skinparam Participant {
    FontColor #000000
    Padding 20
}

skinparam MinClassWidth 100
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
