@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam classFontColor #000000
skinparam classBorderThickness 1.3
skinparam interfaceFontColor #000000

package UI <<Rectangle>>{
Interface Ui <<Interface>> #957DAD
Class "{abstract}\nUiPart" as UiPart #E0BBE4
Class UiManager #E0BBE4
Class MainWindow #FEC8D8
Class HelpWindow #FCE2C2
Class ResultDisplay #FCE2C2
Class PersonListPanel #B3C8C8
Class JobListPanel #B3C8C8
Class PersonAndJobTabPane #FCE2C2
Class PersonCard #4F9EC4
Class JobCard #4F9EC4
Class StatusBarFooter #FCE2C2
Class CommandBox #FCE2C2
Class PersonTab #6CB2D1
Class JobTab #6CB2D1

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StatusBarFooter
MainWindow *-down--> PersonAndJobTabPane

PersonAndJobTabPane *-down-> PersonTab
PersonAndJobTabPane *-down-> JobTab

PersonTab *-down-> PersonListPanel
JobTab *-down-> JobListPanel

PersonListPanel --> PersonCard
JobListPanel --> JobCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
JobCard -down-|> UiPart

JobCard .down..>Model
PersonCard .down..>Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
