@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:UndoPersonCommand" as UndoPersonCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPersonAddressBook" as VersionedPersonAddressBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(undo)
activate AddressBookParser

create UndoPersonCommand
AddressBookParser -> UndoPersonCommand
activate UndoPersonCommand

UndoPersonCommand --> AddressBookParser
deactivate UndoPersonCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UndoPersonCommand : execute()
activate UndoPersonCommand

UndoPersonCommand -> Model : undoPersonAddressBook()
activate Model

Model -> VersionedPersonAddressBook : undo()
activate VersionedPersonAddressBook

VersionedPersonAddressBook -> VersionedPersonAddressBook :resetData(ReadOnly\nPersonAddressBook)
VersionedPersonAddressBook --> Model :
deactivate VersionedPersonAddressBook

Model --> UndoPersonCommand
deactivate Model

UndoPersonCommand --> LogicManager : result
deactivate UndoPersonCommand
UndoPersonCommand -[hidden]-> LogicManager : result
destroy UndoPersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
